### ISSUE TITLE
Issue on Pi Zero

### ISSUE THREAD

**Issue by docpauluk** [lalelunet/measureit#30]
Hi,

I'm tying your latest pre-built image (2016-05-10-raspbian-jessie-lite-measureit-120-2gb) on a Pi Zero and getting the rainbow screen.
Any work-around or fix?

Paul.

**Comment by lalelunet** [comment]
No. I think the image is to old. It is time to build a new one. You are the tester for the Zero because of I do not own one :)

**Comment by docpauluk** [comment]
Happy to help!

**Comment by lalelunet** [comment]
Hi Paul,

it takes some time... I have created a new measureit image. It is based on the latest raspbian image so it should boot on the zero too.

It seems that everything is working fine. Maybe that there are some issues with php because of I replace php5 with php7. You will see it :) 

raspbian-strech-lite-measureit-121-2gb.img
SHASUM 9e08d155aace391956f9413c09ad40ba17809801  

raspbian-strech-lite-measureit-121-2gb.img.zip
SHASUM cda967c31bf2a4ebe1609d730c2958379c715580  

Have fun while playing around with it
https://mega.nz/#!WUtxxC7A!zjJMdC02MjdUqf1kTKHufFTINGcTacV5ferVZSli-b8

**Comment by docpauluk** [comment]
Hi Thomas,

I really appreciate the time and effort you have put into this.
The image loads OK and I can log in but I can't get the Pi Zero's Wifi to
start.
I've set my WiFi country via raspi-config and manually configured my WiFi
credentials and enabled SSH but wlan0 is not coming up.

If I do a ifconfig -a, I see the lo and wlan0 interfaces but no packets on
wlan0.
If I "systemctl status networking.service" I see eth0 but no wlan0...

Any ideas?

Paul

**Comment by lalelunet** [comment]
Hi Paul,

the only difference between the measureit image and the original are the settings in the debian interfaces file. I add there 2 interfaces for wired connections. Maybe this is a problem with the zero because of the missing interface :)

Can you try to remove the interfaces and reboot the zero

File: /etc/network/interfaces

Remove:
auto eth0:1
iface eth0:1 inet static
address 10.0.0.102
netmask 255.255.0.0
gateway 10.0.0.1

auto eth0:2
iface eth0:2 inet static
address 192.168.0.102
netmask 255.255.0.0
gateway 192.168.0.1

**Comment by docpauluk** [comment]
Hi,

Yes, that was the problem.
I commented out those two and rebooted, the WiFi is up and working just fine.
Now to connect up the serial port and start testing...

Many thanks!

Paul

**Comment by Darioits** [comment]
Hi,
I just configured my (new) Raspberry PI 3b+ with your last iso image, and after some little adjustment it worksvery fine (nice project with possibility to some improvement)
How can I set user name and password to my web page, because it's online, and anybody can modify parameters.

Thank you in advance
Dario

**Comment by docpauluk** [comment]
Sorry that I didn't provide feedback sooner - this is still working fine on my Pi Zero W.
